FROM python:3.8-alpine
ENV PYTHONUNBUFFERED=1

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev libffi-dev

RUN mkdir /code
WORKDIR /code

COPY requirements requirements/
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . /code/
