FROM python:3.8-slim
ENV PYTHONUNBUFFERED=1

RUN mkdir /code
WORKDIR /code

COPY requirements requirements/
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . /code/
{% if cookiecutter.deploy_platform == 'heroku_docker' %}
# why this has to be here:
# https://stackoverflow.com/questions/59719175/where-to-run-collectstatic-when-deploying-django-app-to-heroku-using-docker
RUN python manage.py collectstatic --noinput --settings={{ cookiecutter.project_slug }}.settings_heroku

# in Heroku this can also be handled by the run command in heroku.yml
# CMD exec gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 {{ cookiecutter.project_slug }}.wsgi:application
{% endif %}{% if cookiecutter.deploy_platform == 'digital_ocean_app_platform' %}
# note: if you don't want to run collectstatic on every deploy you can remove this lines.
RUN python manage.py collectstatic --noinput --settings={{ cookiecutter.project_slug }}.settings_do
{% endif %}{% if cookiecutter.deploy_platform == 'google_cloud_run' %}
CMD exec gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 {{ cookiecutter.project_slug }}.wsgi:application
{% endif %}
