FROM python:3.8-slim
ENV PYTHONUNBUFFERED=1

RUN mkdir /code
WORKDIR /code

COPY requirements requirements/
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . /code/

# note: if you don't want to run collectstatic on every deploy you can remove this lines.
RUN python manage.py collectstatic --noinput --settings=pega.settings_do

