# Generated by Django 3.1.4 on 2021-03-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isfree',
            field=models.BooleanField(default=False),
        ),
    ]
