# Generated by Django 3.1.4 on 2021-03-13 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_isfree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='isfree',
        ),
    ]
