# Generated by Django 3.1.4 on 2021-03-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_isfree'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_mailerlite',
            field=models.BooleanField(default=False),
        ),
    ]
