# Generated by Django 3.1.4 on 2021-03-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_is_mailerlite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_mailerlite',
            field=models.BooleanField(default=True),
        ),
    ]
