# Generated by Django 3.1.4 on 2020-12-14 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atrributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.CharField(max_length=100)),
                ('api_attribute', models.CharField(max_length=100)),
                ('value_assigned', models.CharField(max_length=100)),
                ('api_value', models.CharField(max_length=100)),
                ('words_matched', models.CharField(max_length=100)),
                ('user_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Extractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('types', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('words_matched', models.CharField(max_length=100)),
                ('user_id', models.PositiveIntegerField()),
                ('enabled', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('example', models.CharField(max_length=100)),
                ('required', models.CharField(max_length=100)),
                ('feed_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('example', models.CharField(max_length=100)),
                ('required', models.CharField(max_length=100)),
                ('feed_channel_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uniqueid', models.UUIDField(default=uuid.uuid4)),
                ('types', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('manage_enabled', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('types', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('value_api', models.CharField(max_length=100)),
                ('example', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('enabled', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntelGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uniqueid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('plan_id', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('intelgroup_id', models.PositiveIntegerField()),
                ('types', models.CharField(max_length=100)),
                ('annual_price', models.PositiveIntegerField()),
                ('monthly_price', models.PositiveIntegerField()),
                ('max_feeds', models.PositiveIntegerField()),
                ('max_users', models.PositiveIntegerField()),
                ('enabled_custom_feeds', models.CharField(max_length=100)),
                ('enabled_api', models.PositiveIntegerField()),
                ('enabled_custom_extraction', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroupRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveIntegerField()),
                ('intelgroup_id', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Whitelists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator_type', models.CharField(max_length=100)),
                ('indicator_value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
