# Generated by Django 3.1.4 on 2020-12-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20201222_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extractions',
            old_name='user_id',
            new_name='user',
        ),
    ]
