# Generated by Django 3.1.4 on 2020-12-23 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_auto_20201222_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicators',
            name='user_id',
        ),
        migrations.AddField(
            model_name='indicators',
            name='type_api',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicators',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
