# Generated by Django 3.1.4 on 2020-12-23 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_auto_20201223_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelists',
            old_name='indicator_type',
            new_name='whitelist',
        ),
        migrations.RemoveField(
            model_name='whitelists',
            name='indicator_value',
        ),
        migrations.AddField(
            model_name='whitelists',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.indicators'),
        ),
        migrations.AddField(
            model_name='whitelists',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
