# Generated by Django 3.1.4 on 2020-12-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20201223_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelists',
            old_name='whitelist',
            new_name='value',
        ),
    ]
