# Generated by Django 3.1.4 on 2020-12-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20201223_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelists',
            name='enabled',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
