# Generated by Django 3.1.4 on 2020-12-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_whitelists_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='max_feeds',
            field=models.CharField(max_length=100),
        ),
    ]
