# Generated by Django 3.1.4 on 2020-12-30 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20201229_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedchannels',
            name='uniqueid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='webhooks',
            name='uniqueid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
