# Generated by Django 3.1.4 on 2020-12-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20201230_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='intelgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.intelgroups'),
        ),
    ]
