# Generated by Django 3.1.4 on 2020-12-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20201230_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedchannels',
            name='feed_id',
        ),
        migrations.RemoveField(
            model_name='feeditems',
            name='feed_channel_id',
        ),
        migrations.AddField(
            model_name='feedchannels',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.feeds'),
        ),
        migrations.AddField(
            model_name='feeditems',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.feeds'),
        ),
    ]
