# Generated by Django 3.1.4 on 2020-12-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20201230_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedchannels',
            name='atomlink',
            field=models.TextField(default=''),
        ),
    ]
