# Generated by Django 3.1.4 on 2020-12-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_feedchannels_atomlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedchannels',
            name='atomlink',
        ),
    ]
