# Generated by Django 3.1.4 on 2020-12-30 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_remove_feedchannels_atomlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicators',
            name='user',
        ),
        migrations.AddField(
            model_name='indicators',
            name='feeditem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.feeditems'),
        ),
    ]
