# Generated by Django 3.1.4 on 2020-12-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20201230_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='example',
            field=models.TextField(default=''),
        ),
    ]
