# Generated by Django 3.1.4 on 2020-12-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20201230_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='enabled',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='type_api',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='types',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='value',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='value_api',
            field=models.CharField(default='', max_length=100),
        ),
    ]
