# Generated by Django 3.1.4 on 2021-01-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_tags_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='', max_length=100)),
                ('type_api', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
                ('value_api', models.CharField(default='', max_length=100)),
                ('enabled', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
