# Generated by Django 3.1.4 on 2021-01-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_globalindicators_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicators',
            name='type_api',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='types',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='value',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='value_api',
        ),
        migrations.AddField(
            model_name='indicators',
            name='globalindicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.globalindicators'),
        ),
    ]
