# Generated by Django 3.1.4 on 2021-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20210103_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedchannels',
            name='category',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='cloud',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='copyright',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='docs',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='generator',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='image',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='language',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='lastbuilddate',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='link',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='managingeditor',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='pubdate',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='skipdays',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='skiphours',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='textinput',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='title',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='ttl',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedchannels',
            name='webmaster',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feeditems',
            name='author',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feeditems',
            name='category',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feeditems',
            name='comments',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feeditems',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feeditems',
            name='enclosure',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feeditems',
            name='guid',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feeditems',
            name='link',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feeditems',
            name='pubdate',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feeditems',
            name='source',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='feeditems',
            name='title',
            field=models.TextField(default='', null=True),
        ),
    ]
