# Generated by Django 3.1.4 on 2021-01-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_auto_20210103_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterField(
            model_name='intelgroups',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='intelgroups',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
