# Generated by Django 3.1.4 on 2021-01-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_auto_20210106_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
