# Generated by Django 3.1.4 on 2021-01-12 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0033_auto_20210106_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.CharField(default='', max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
                ('words_matched', models.CharField(default='', max_length=100)),
                ('enabled', models.CharField(default='Enable', max_length=100)),
                ('intelgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.intelgroups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
