# Generated by Django 3.1.4 on 2021-01-12 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0034_globalattributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atrributes',
            name='user_id',
        ),
        migrations.AddField(
            model_name='atrributes',
            name='enabled',
            field=models.CharField(default='Enable', max_length=100),
        ),
        migrations.AddField(
            model_name='atrributes',
            name='intelgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.intelgroups'),
        ),
        migrations.AddField(
            model_name='atrributes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atrributes',
            name='api_attribute',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='atrributes',
            name='api_value',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='atrributes',
            name='attribute',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='atrributes',
            name='value_assigned',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='atrributes',
            name='words_matched',
            field=models.CharField(default='', max_length=100),
        ),
    ]
