# Generated by Django 3.1.4 on 2021-01-12 19:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0035_auto_20210112_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atrributes',
            new_name='Attributes',
        ),
    ]
