# Generated by Django 3.1.4 on 2021-01-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_auto_20210112_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributes',
            old_name='value_assigned',
            new_name='value',
        ),
    ]
