# Generated by Django 3.1.4 on 2021-01-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0006_2_3'),
        ('project', '0038_auto_20210113_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelgroups',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.subscription'),
        ),
    ]
