# Generated by Django 3.1.4 on 2021-01-18 22:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0006_2_3'),
        ('project', '0039_auto_20210116_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributes',
            options={'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterModelOptions(
            name='feeds',
            options={'verbose_name_plural': 'Feeds'},
        ),
        migrations.AlterModelOptions(
            name='intelgroups',
            options={'verbose_name_plural': 'IntelGroups'},
        ),
        migrations.AlterField(
            model_name='intelgroups',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='intelgroups',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.subscription'),
        ),
        migrations.AlterField(
            model_name='intelgroups',
            name='uniqueid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
