# Generated by Django 3.1.4 on 2021-01-18 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_auto_20210116_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributes',
            options={'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterModelOptions(
            name='feeds',
            options={'verbose_name_plural': 'Feeds'},
        ),
        migrations.AlterModelOptions(
            name='intelgroups',
            options={'verbose_name_plural': 'IntelGroups'},
        ),
        migrations.AlterField(
            model_name='intelgroups',
            name='uniqueid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
