# Generated by Django 3.1.4 on 2021-01-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_auto_20210118_2152'),
        ('project', '0040_auto_20210118_2211'),
    ]

    operations = [
    ]
