# Generated by Django 3.1.4 on 2021-01-19 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_auto_20210118_2221'),
        ('project', '0040_auto_20210118_2211'),
    ]

    operations = [
    ]
