# Generated by Django 3.1.4 on 2021-01-19 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0006_2_3'),
        ('project', '0045_merge_20210119_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('intelgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.intelgroups')),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.AlterField(
            model_name='feeds',
            name='uniqueid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
