# Generated by Django 3.1.4 on 2021-01-19 05:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_merge_20210119_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='uniqueid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
