# Generated by Django 3.1.4 on 2021-01-22 02:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_auto_20210119_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feeditem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.feeditems')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
