# Generated by Django 3.1.4 on 2021-01-22 17:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_auto_20210122_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='isglobal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeds',
            name='polltime',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
