# Generated by Django 3.1.4 on 2021-01-24 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_auto_20210122_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooks',
            name='isenable',
            field=models.BooleanField(default=True),
        ),
    ]
