# Generated by Django 3.1.4 on 2021-01-22 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_auto_20210122_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plans',
        ),
        migrations.AlterField(
            model_name='feeds',
            name='uniqueid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
