# Generated by Django 3.1.4 on 2021-01-25 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_auto_20210125_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeds',
            name='polltime',
        ),
        migrations.AddField(
            model_name='feeds',
            name='time',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
