# Generated by Django 3.1.4 on 2021-01-26 01:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0052_auto_20210125_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('annual_amount', models.PositiveIntegerField(default=0)),
                ('monthly_amount', models.PositiveIntegerField(default=0)),
                ('max_users', models.PositiveIntegerField(default=0)),
                ('max_feeds', models.PositiveIntegerField(default=0)),
                ('custom_observables', models.BooleanField(default=False)),
                ('custom_feeds', models.BooleanField(default=False)),
                ('api_access', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='plan',
            name='interval',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
