# Generated by Django 3.1.4 on 2021-01-27 13:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_auto_20210126_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGlobalAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isenable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='globalattributes',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='globalattributes',
            name='intelgroup',
        ),
        migrations.RemoveField(
            model_name='globalattributes',
            name='user',
        ),
        migrations.AddField(
            model_name='groupglobalattributes',
            name='globalattribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.globalattributes'),
        ),
        migrations.AddField(
            model_name='groupglobalattributes',
            name='intelgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.intelgroups'),
        ),
    ]
