# Generated by Django 3.1.4 on 2021-01-29 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0054_auto_20210127_1344'),
    ]

    operations = [
    ]
