# Generated by Django 3.1.4 on 2021-01-29 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0055_auto_20210129_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='enabled',
        ),
        migrations.AddField(
            model_name='attributes',
            name='isenable',
            field=models.BooleanField(default=True),
        ),
    ]
