# Generated by Django 3.1.4 on 2021-01-30 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0057_auto_20210130_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extractions',
        ),
    ]
