# Generated by Django 3.1.4 on 2021-01-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0059_auto_20210131_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicators',
            name='enabled',
        ),
        migrations.AddField(
            model_name='indicators',
            name='isenable',
            field=models.BooleanField(default=True),
        ),
    ]
