# Generated by Django 3.1.4 on 2021-01-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0060_auto_20210131_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalattributes',
            options={'verbose_name_plural': 'GlobalAttributes'},
        ),
        migrations.AlterModelOptions(
            name='groupplan',
            options={'verbose_name_plural': 'GroupPlan'},
        ),
        migrations.RemoveField(
            model_name='tags',
            name='state',
        ),
        migrations.AddField(
            model_name='tags',
            name='isglobal',
            field=models.BooleanField(default=False),
        ),
    ]
