# Generated by Django 3.1.4 on 2021-02-02 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0061_auto_20210131_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='intelgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.intelgroups'),
        ),
    ]
