# Generated by Django 3.1.4 on 2021-02-04 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_auto_20210203_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='user',
        ),
        migrations.AddField(
            model_name='tags',
            name='intelgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.intelgroups'),
        ),
    ]
