# Generated by Django 3.1.4 on 2021-02-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0064_auto_20210204_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelists',
            name='indicator',
        ),
        migrations.AddField(
            model_name='whitelists',
            name='globalindicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.globalindicators'),
        ),
    ]
