# Generated by Django 3.1.4 on 2021-02-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_auto_20210204_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikeys',
            name='intelgroup',
        ),
        migrations.AddField(
            model_name='apikeys',
            name='groupids',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
