# Generated by Django 3.1.4 on 2021-02-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_auto_20210206_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='groupplan',
            options={'verbose_name_plural': 'GroupPlans'},
        ),
        migrations.AddField(
            model_name='groupplan',
            name='daily_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupplan',
            name='weekly_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
