# Generated by Django 3.1.4 on 2021-02-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0071_groupplan_group_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupplan',
            name='group_public',
            field=models.BooleanField(default=True),
        ),
    ]
