# Generated by Django 3.1.4 on 2021-03-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0073_auto_20210305_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('intelgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.intelgroups')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
