# Generated by Django 3.1.4 on 2021-03-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0074_inviteemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelgroups',
            name='isfree',
            field=models.BooleanField(default=False),
        ),
    ]
