# Generated by Django 3.1.4 on 2021-03-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0075_intelgroups_isfree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeds',
            name='intelgroup',
        ),
    ]
