# Generated by Django 3.1.4 on 2021-03-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0076_remove_feeds_intelgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGlobalIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isenable', models.BooleanField(default=True)),
                ('globalindicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.globalindicators')),
                ('intelgroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.intelgroups')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
