# Generated by Django 3.1.4 on 2021-03-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0077_groupglobalindicators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicators',
            name='isenable',
        ),
    ]
